version: '3.1'

services:
  mongo:
    image: mongo:8.0.4
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: password
  reline-backend:
    image: wukashr/reline-backend:1.0
    restart: always
    ports:
      - "8080:8080"
  reline-ui:
    image: wukashr/revezo/reline-ui:1.0
    restart: always
    ports:
      - "80:80"

